config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clearance_batches, only: [:index, :create, :show]

  namespace :api, format: :json do
    namespace :v1 do
      resources :clearance_batches, only: [:show]
    end
  end
  root to: "clearance_batches#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clearance_batch.rb
class ClearanceBatch < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")
  MINIMUM_PRICE_OTHERS  = BigDecimal.new("2.00")
  MINIMUM_PRICE_DRESS_AND_PANTS  = BigDecimal.new("5.00")

  belongs_to :style
  belongs_to :clearance_batch

  enum status: [:sellable, :clearanced]
  enum size: [:XS, :S, :M, :L, :XL, :XXL ]
  enum color: [:purple, :blue, :red, :white, :orange, :green, :navy, :black, :turquoise]

  def clearance!
    update_attributes!(status: 'clearanced', 
                       price_sold: sale_price)
  end

  private

  def sale_price
    value = style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE
    value < minimum_price ? minimum_price : value
  end

  def minimum_price
    style.dress? || style.pants? ? MINIMUM_PRICE_DRESS_AND_PANTS : MINIMUM_PRICE_OTHERS
  end
end

app/models/style.rb
class Style < ApplicationRecord
  self.inheritance_column = :_type_disabled
  has_many :items

  enum type: [:sweater, :top, :dress, :pants, :scarf]
end

app/controllers/api/v1/clearance_batches_controller.rb
class Api::V1::ClearanceBatchesController < ApplicationController
  def show
    @batch = ClearanceBatch.find(params[:id])

    render json: @batch, serializer: ClearanceBatchSerializer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin_user!
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController

  def index
    @clearance_batches  = ClearanceBatch.all
  end

  def create
    clearancing_status = ClearancingService.new.process_file(params[:csv_batch_file].tempfile)
    clearance_batch    = clearancing_status.clearance_batch
    alert_messages     = []
    if clearance_batch.persisted?
      flash[:notice]  = "#{clearance_batch.items.count} items clearanced in batch #{clearance_batch.id}"
    else
      alert_messages << "No new clearance batch was added"
    end
    if clearancing_status.errors.any?
      alert_messages << "#{clearancing_status.errors.count} item ids raised errors and were not clearanced"
      clearancing_status.errors.each {|error| alert_messages << error }
    end
    flash[:alert] = alert_messages.join("<br/>") if alert_messages.any?
    redirect_to action: :index
  end

  def show
    @clearance_batch = ClearanceBatch.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_batches/index.html.erb
<h2>Clearance Batches</h2>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'csv_batch_file', 'Select batch file' %>
    <%= file_field_tag 'csv_batch_file', class: 'form-control' %>
  </div>
  <%= button_tag 'upload batch file', class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped clearance_batches">
  <thead>
    <tr>
      <th></th>
      <th>Date clearanced</th>
      <th>Number of items clearanced</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%- @clearance_batches.each do |clearance_batch| -%>
      <tr>
        <td><%= link_to "Clearance Batch #{clearance_batch.id}", clearance_batch_path(clearance_batch) %></td>
        <td><%= l(clearance_batch.created_at, format: :short) %></td>
        <td><%= clearance_batch.items.count %></td>
        <td><%= link_to "View", clearance_batch_path(clearance_batch) %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/clearance_batches/show.html.erb
<h2><%= "Clearance Batch #{@clearance_batch.id}" %></h2>

<table id="clearance-batch" class="table table-striped clearance_batches" data-batch-id="<%= @clearance_batch.id %>">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Style</th>
      <th>Size</th>
      <th>Color</th>
      <th>Price Sold</th>
    </tr>
  </thead>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <span class="navbar-brand">First Circle Inventory Management</span>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right logout">
          <li>
            <%= link_to "Admin Panel", admin_root_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_admin_user_session_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
  <div class="content">
    <%= yield %>
  </div>
</div>

</body>
</html>